<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["riderUser/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["riderUser/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Mobile</th>
            <th>Name</th>
            <th>Rider Of Company</th>
            <th>Rider Of Site</th>
            <th>Idcard Of Img</th>
            <th>Health Of Img</th>
            <th>Status</th>
            <th>Is Of Delete</th>
            <th>Create Of Time</th>
            <th>Longitude</th>
            <th>Latitude</th>
            <th>Update Of Time</th>
            <th>Password</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $rp_rider_user): ?>
            <tr>
                <td><?php echo $rp_rider_user->id ?></td>
            <td><?php echo $rp_rider_user->mobile ?></td>
            <td><?php echo $rp_rider_user->name ?></td>
            <td><?php echo $rp_rider_user->rider_company_id ?></td>
            <td><?php echo $rp_rider_user->rider_site_id ?></td>
            <td><?php echo $rp_rider_user->idcard_img ?></td>
            <td><?php echo $rp_rider_user->health_img ?></td>
            <td><?php echo $rp_rider_user->status ?></td>
            <td><?php echo $rp_rider_user->is_delete ?></td>
            <td><?php echo $rp_rider_user->create_time ?></td>
            <td><?php echo $rp_rider_user->longitude ?></td>
            <td><?php echo $rp_rider_user->latitude ?></td>
            <td><?php echo $rp_rider_user->update_time ?></td>
            <td><?php echo $rp_rider_user->password ?></td>

                <td><?php echo $this->tag->linkTo(["riderUser/edit/" . $rp_rider_user->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["riderUser/delete/" . $rp_rider_user->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-2">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
            &emsp;共：<?php echo $page->total_items ?>记录
        </p>
    </div>
    <div class="col-sm-10">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("riderUser/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("riderUser/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("riderUser/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("riderUser/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
